invokers/python/setup.py

There was a recent update to MarkupSafe's minor version which broke API compatability. This affected a library `Jinja2` used by `Flask`.
Flask 1.x is no longer actively worked on, and thus the breaking change will remain unless we pin to an older version of `MarkupSafe`. We decided to update to Flask 2 instead.

Update flask dependency to X where 2 <= X < 3

---

invokers/python/pyfunc/__main__.py
invokers/python/pyfunc/invoke.py
invokers/python/setup.py

#53 
This replaces the usage of the built-in flask webserver with waitress.
```release-note
* Added new dependency on waitress
* Replaced built-in flask webserver with waitress
```
Ran it locally.
The [license](https://github.com/Pylons/waitress/blob/master/LICENSE.txt) for waitress is Zope Public License (ZPL) 2.1.
According to [wikipedia](https://en.wikipedia.org/wiki/Zope_Public_License), this is OSI and FSF approved.
[TLDRLegal](https://tldrlegal.com/license/zope-public-license-2.1-(zpl-2.1)) looks pretty permissive as well.
I am not a lawyer.

Use python waitress server instead of the flask built-in

---

buildpacks/python/buildpack.toml
buildpacks/python/go.sum
buildpacks/python/python/build.go
buildpacks/python/python/invoker.go
buildpacks/python/python/invoker_dependency_cache.go

Part of: #56 
This adds the cached dependencies for running the invoker.
```release-note
Invoker dependencies are now fetched and cached onto the image so it doesn't need to be pulled during install time.
```

Add python invoker dependency as buildpack dependency (offline usecase)

---

manifest.yaml

Signed-off-by: Fabian Lopez <lfabian@vmware.com>
Partially fixes: #30
Makes templates usable by `kn func create`
```release-note
Create via kn-func can now make use the java and python templates from this repo:
kn func create -r https://github.com/vmware-tanzu/function-buildpacks-for-knative.git -l java -t (cloudevents-maven|cloudevents-gradle|http-maven|http-gradle)
kn func create -r https://github.com/vmware-tanzu/function-buildpacks-for-knative.git -l python -t (cloudevents|http)
```
Created a fork for this repo and by making the same changes in this PR to the `manifest.yaml` I was able to create functions by pointing to my fork with the `-r` flag
As mentioned in the linked issue, there still is the problem of building the generated functions with our buildpacks

Make templates usable for func create

---

samples/java/cloudevents/txt-to-pdf-maven/Makefile
samples/python/cloudevents/s3_lamba/README.md
samples/python/cloudevents/sqs-lambda/README.md
samples/python/cloudevents/txt-to-pdf/Makefile
samples/python/http/adder/README.md
templates/java/manifest.yaml
templates/python/manifest.yaml

Fixes a potential bug with `kn func` CLI failing to build our functions (it currently pulls us.gcr.io/daisy-284300/kn-fn/builder:0.0.6)
Potentially solves a bug; at worst, updates the builder to be our latest one and properly targeting GHCR instead.
```release-note
Update samples / templates to use builder@v0.0.10
```
n/a
n/a

Update examples to use latest builder

---

buildpacks/python/README.md
buildpacks/python/buildpack.toml
buildpacks/python/python/detect.go

Fixes: #63 
This adds two configuration options for the buildpack.
`BP_FUNCTION` to specify the Python module and function.
Tested it on our sample. (with func.yaml | it detects and builds the image)
Tested it on our sample. (without func.yaml | it fails detect, this was expected)
Tested it on our sample. (without func.yaml but specified env variables | it detects and builds the image) 
Alternatively I can switch this to the split version.
Looking for opinions!

Add check for configuration value to set function handler via CLI

---

samples/java/cloudevents/txt-to-pdf-maven/config/100-namespace.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/200-broker.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/200-secret.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/200-source.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/200-trigger.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/300-app-secret.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/function.yaml
samples/java/cloudevents/txt-to-pdf-maven/config/values.yaml
samples/python/cloudevents/txt-to-pdf/config/100-namespace.yaml
samples/python/cloudevents/txt-to-pdf/config/200-broker.yaml
samples/python/cloudevents/txt-to-pdf/config/200-secret.yaml
samples/python/cloudevents/txt-to-pdf/config/200-source.yaml
samples/python/cloudevents/txt-to-pdf/config/200-trigger.yaml
samples/python/cloudevents/txt-to-pdf/config/300-app-secret.yaml
samples/python/cloudevents/txt-to-pdf/config/function.yaml
samples/python/cloudevents/txt-to-pdf/config/values.yaml

The automated copyright headers commit broke ytt functionality.

fix: ytt cannot have headers as comments

---

buildpacks/java/README.md
buildpacks/java/java/build.go
buildpacks/java/java/detect.go
buildpacks/java/java/function.go
buildpacks/java/ytt/buildpack.yaml
samples/java/cloudevents/txt-to-pdf-maven/Makefile

We are going to support Functions in the way of 
```java
package com.organization.functions
class MyFunction implements Function<T,F> {
@Override
public F apply(T obj) {
.... // Code here
}
}
```
so the attribute `BP_DEFAULT_FUNCTION` is not going to be used if defined.
To point to the function the user will specify `BP_FUNCTION=packageName.ClassName`. 
For Example,
```bash
pack .... --env BP_FUNCTION=com.organization.functions.MyFunction
```

feat: delete the use of BP_DEFAULT_FUNCTION

---

.github/actions/srp-helper/submit/submit.sh

SRP had an issue where unencoded `/` would cause validation errors. It now properly accepts `/` in the UID.
For reference: https://vmware.slack.com/archives/C03GZ0FHSNL/p1659645104770439

chore: SRP now properly accept unencoded UID

---

builder/ytt/builder.yaml
buildpacks/java/ytt/buildpack.yaml
buildpacks/java/ytt/dependencies.yaml
buildpacks/python/ytt/buildpack.yaml
buildpacks/python/ytt/dependencies.yaml

This PR updates our Python and Java to use Buildpack API version 0.7 and will now target all stacks

Bump buildpack API version and change stack to wildcard

---

invokers/python/Dockerfile

This addresses an issue where a version of python (non 3.9) is used and installing the dependency will cause it to fail.
This isn't seen if we are "online" but in an "offline" situation, this will fail to run our invoker.

Fetch the non-binary version of MarkupSafe

---

buildpacks/python/python/invoker.go
buildpacks/python/python/invoker_dependency_cache.go

The workaround addresses an issue with libpak where a comaprison fails because of a `nil` in the CPEs when none is specified.
https://github.com/paketo-buildpacks/libpak/issues/167

fix(python-buildpack): add workaround for offline python-buildpack

---

buildpacks/python/python/detect.go

One of the buildpacks we depend on looks like no longer transitively
include python at launch time. We will now be explicit in the required
buildpacks to prevent future breakage.

fix(python-buildpack): Explicitly require python for build and launch

---

buildpacks/python/ytt/buildpack.yaml

Libpak is working on adding support cycloneDX. Adding the SBOM format for the future.

feat(python-buildpack): Add support for cycloneDX SBOM when available.

---

buildpacks/python/python/invoker.go
buildpacks/python/python/invoker_dependency_cache.go
buildpacks/python/ytt/dependencies.yaml
buildpacks/python/ytt/dependency-metadata.yaml

This removes the workaround/hack for the libpak bug. Added CPEs and pURL for the python dependencies we pull in. We are currently doing it manually but we should automate this at some point.

chore(python-buildpack): Add CPEs and pURL to python buildpack dependencies

---

buildpacks/python/python/build.go

The `shell` entrypoint was meant for debugging, use the following commands to achieve the same result:
`docker run -it --entrypoint launcher <image_name> /bin/bash`

chore(python-buildpack): Remove unnecessary entrypoint

---

tests/template_test.go

Skips the test that broke due to Spring Cloud Function's non-disclosed breaking change in CloudEvent Headers.
```
=== RUN   TestJavaCloudEventsOverHTTP
=== RUN   TestJavaCloudEventsOverHTTP/Java_CloudEvents_Gradle
template_test.go:413: Skipped: Expected failure because Spring Cloud Functions broke CloudEvent Header handling.
template_test.go:414:
=== RUN   TestJavaCloudEventsOverHTTP/Java_CloudEvents_Maven
template_test.go:413: Skipped: Expected failure because Spring Cloud Functions broke CloudEvent Header handling.
template_test.go:414:
--- PASS: TestJavaCloudEventsOverHTTP (62.06s)
--- SKIP: TestJavaCloudEventsOverHTTP/Java_CloudEvents_Gradle (31.02s)
--- SKIP: TestJavaCloudEventsOverHTTP/Java_CloudEvents_Maven (31.04s)
PASS
ok  	kn-fn/buildpack-tests	278.242s
```
Signed-off-by: Bryan …

fix: Skip test broken by SCF

---

builder/ytt/builder.yaml
builder/ytt/java.yaml
builder/ytt/nodejs.yaml
builder/ytt/python.yaml
buildpacks/java/java/detect.go

This change updates the builder to use latest versions of the buildpacks for Java, Python and NodeJS.
The builder's focus is now specifically functions, if the functions buildpack doesn't get activated this builder won't do anything. It's no longer intended for use to build plain ol java or python applications.
**We will need to first cut new invokers and new buildpacks to maybe have passing tests for this PR.**

feat(builder): Update buildpacks to support jammy stack

---

.gitignore
CONTRIBUTING.md
Makefile
local.example.mk
rules.mk
tests/README.md

- Updates default registry location to one that will work when running `make tests` out of the gate
- Adds ability to easily override registry location with local config (that isn't version-controlled) via a `local.mk` file
- Updates docs for clarity

Make contributing a bit easier/clearer

---

invokers/java/pom.xml

There was a bug in SCF version 3.1.4-3.2.7 where it doesn't process HTTP structured CloudEvents.

fix(java-invoker): update Spring Cloud Function to 3.2.8-SNAPSHOT

---

buildpacks/java/ytt/dependency-metadata.yaml

I forgot to update this when I bumped the version. We should see if we can automate this eventually.

fix(java-buildpack): update CPE for java-buildpack

---

buildpacks/common/go.mod
buildpacks/common/tests/func_yaml_test.go
buildpacks/java/go.mod
buildpacks/java/tests/detect_test.go
buildpacks/python/go.mod
buildpacks/python/tests/detect_test.go

Remove dependency on knative dev pkg in the buildpack tests

Remove dependency on knative dev pkg in the buildpack tests

---

buildpacks/java/java/detect.go
buildpacks/java/tests/detect_test.go

Fixes a small area in the java buildpack tests where we neglected to use the testing-specific `t.Setenv` (note the `t.`). We were using `os.Unsetenv` instead (note the `os.`). This also leads us to treat an empty env var similarly to an unset env var -- which is good to do anyway -- because there is no `t.Unsetenv()` and we have to use `t.Setenv(..., "")` instead.
For the curious, here's a thread on the reasoning behind no `t.Unsetenv`: https://github.com/golang/go/issues/52817. Essentially, the argument is that it's unnecessary because `t.Setenv(..., "")` should be used instead (and empty vars should be treated like unset vars).

fix(java-buildpack): Treat empty BP_FUNCTION the same as unset

---

DEPLOYING.md
buildpacks/java/README.md
buildpacks/python/README.md
samples/java/cloudevents/txt-to-pdf-gradle/Makefile
samples/java/cloudevents/txt-to-pdf-gradle/func.yaml
samples/java/cloudevents/txt-to-pdf-maven/Makefile
samples/java/cloudevents/txt-to-pdf-maven/spring-java-fn/func.yaml
samples/java/http/request-response-gradle/Makefile
samples/java/http/request-response-gradle/func.yaml
samples/java/http/request-response-maven/Makefile
samples/java/http/request-response-maven/func.yaml
samples/python/cloudevents/s3-lambda/README.md
samples/python/cloudevents/s3-lambda/func.yaml
samples/python/cloudevents/sqs-lambda/README.md
samples/python/cloudevents/sqs-lambda/knative-function-encrypter/func.yaml
samples/python/cloudevents/txt-to-pdf/app/func.yaml
samples/python/http/adder/README.md
samples/python/http/adder/func.yaml
templates/java/cloudevents-gradle/func.yaml
templates/java/cloudevents-maven/func.yaml
templates/java/http-gradle/func.yaml
templates/java/http-maven/func.yaml
templates/python/cloudevents/func.yaml
templates/python/http/func.yaml
tests/testdata/template_and_smoke/template-ce/Makefile
tests/testdata/template_and_smoke/template-http/Makefile

This commit updates documentation to account for the latest version of https://github.com/knative/func which has requirements for valid func.yaml files.  It also removes func.yaml files and updates tests to use the BP_FUNCTION environment variable. 

Chore(tests, docs): Update after Knative func cli updates

---

.gitignore
rules.mk
tests/testdata/template_and_smoke/template-ce/Makefile
tests/testdata/template_and_smoke/template-ce/java-cloudevents-gradle
tests/testdata/template_and_smoke/template-ce/java-cloudevents-maven
tests/testdata/template_and_smoke/template-ce/python-cloudevents
tests/testdata/template_and_smoke/template-http/Makefile
tests/testdata/template_and_smoke/template-http/java-http-gradle
tests/testdata/template_and_smoke/template-http/java-http-maven
tests/testdata/template_and_smoke/template-http/python-http

To work with the knative func CLI for our templates, there is a bug where a symlink to a directory will cause it to fail cloning our templates.
This will address that issue for now, as we'll generate these symlinks at test time only.

chore(template-tests): generate symlinks at test time

---

templates/java/manifest.yaml
templates/python/manifest.yaml

Fixes: #23 
Makes Java and Python templates compatible with kn-func cli plugin
```release-note
Replace buildpack builder in Java and Python func templates to use buildpacks images with default builder
```
Built images from templates with the latest version of kn-func plugin
The Java template requires the builder image to be specified because there's no default image for the `java` runtime if we wanted for the template to use the default builder without setting it in the template's manifest we should rename the folder to what the func plugin expects `springboot`

specify buildpack images instead of builder

---

.github/actions/semver-bump/.gitignore
.github/workflows/create-builder-release.yaml
.github/workflows/create-buildpack-release.yaml
.github/workflows/create-invoker-release.yaml
.gitignore

Some of our scripts in the GitHub actions are subject to [script injection attacks](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections).
We can
* [Use an action instead of an inline script](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-action-instead-of-an-inline-script-recommended)
* Using [intermediate environment variables](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable) 
we can fix it by storing the evaluation in a variable before using it.

Fix script injection attacks

---

tests/testdata/template_and_smoke/echo-ce/Makefile
tests/testdata/template_and_smoke/helloworld/Makefile
tests/testdata/template_and_smoke/template-ce/Makefile
tests/testdata/template_and_smoke/template-http/Makefile

Java 17 is required since Spring 3 is now used for Java Invoker.  Environment variable BP_JVM_VERSION is required until buildpacks default to Java 17 instead of 11.

JVM 17 is required since Spring 3 is now used for Java Invoker

---

.github/actions/srp-helper/install/action.yml
.github/workflows/vmware-srp-report.yaml

SRP is not running since moving the urls to secrets. Fix it by passing secrets from the top workflow to the called workflow using the "with:" syntax.

chore(srp) Enable SRP to run again

---

CONTRIBUTING.md

We have tags for each buildpack, invoker, and builder version but if we have different versions (minor, major) we should keep release branches. For example, we needed to patch java-buildpack/v1.0.X and there was no branch for it but a tag to the last version. What we did was to create a java-buildpack/v1.0.x branch and now every 1.0.<nextpatch> will be cut from that branch.
 
Go over the branches and versions of our products in the repository and create release branches. Also, update dthe release documentation to reflect the patching process of these resources.

add patch development guidelines

---

invokers/python/Dockerfile

This PR may resolve an issue with tanzu-python's failing Action's integration test.

Require setuptools>=40.8.0

---

CONTRIBUTING.md
DEPLOYING.md
NOTICE
README.md

add deprecation warnings to READMEs

---

MIGRATION.md
README.md

Now that the the set of buildpacks are going out of support we need to guide the users into a new path

add migration guide for users
