vmware-tanzu/function-buildpacks-for-knative

manifest.yaml
templates/java/manifest.yaml
templates/python/manifest.yaml

Fixes: #1 #2 
Adds the required `manifest.yaml`'s for our templates to work with `func` CLI.
```release-note
Add manifest.yaml for func CLI support
```
N/A
Based off of existing work [in the func repo
](https://github.com/knative-sandbox/kn-plugin-func/tree/main/templates/python)

Add barebones manifest.yaml's

---

buildpacks/java/go.mod
buildpacks/java/go.sum

This is a test of the new Dependency Check Action that we are adding.

Add test dep bump

---

buildpacks/java/java/build.go

Fixes: #28 
```release-note
The builder now detects when a java project includes the `tomcat-embed-core` dependency and avoids adding the invoker layer so tomcat and the invoker don't collide
```
- Created java (gradle and maven) projects with the `spring-starter-web` dependency that refused to start when built with `function-buildpacks-for-knative` 🟢 
- Skipped adding the invoker layer when the embedded tomcat dependency is present 🟢 
- Verified that projects including the embedded tomcat dependency start correctly and endpoints are accessible 🟢 
- Verified that sample java projects that don't include the tomcat dependency still work as expected ❌ 
Actually both the maven and gradle sample containers start but don't expose the function as an endpoint I assume because some spring-cloud …

Embedded tomcat skips invoker layer

---

.github/actions/srp-helper/check-srp-creds/action.yml
.github/actions/srp-helper/check-srp-creds/check.sh
.github/actions/srp-helper/collect/action.yml
.github/actions/srp-helper/collect/collect.sh
.github/actions/srp-helper/init/action.yml
.github/actions/srp-helper/init/init.sh
.github/actions/srp-helper/install/action.yml
.github/actions/srp-helper/install/install.sh
.github/actions/srp-helper/submit/action.yml
.github/actions/srp-helper/submit/submit.sh
.github/workflows/vmware-srp-report.yaml

This creates a new workflow for SRP reporting when we publish new packages for invoker and buildpacks.

Add vmware SRP Reporting

---

invokers/python/pyfunc/invoke.py
invokers/python/tests/invoke_test.py

fix: Use make_response instead of Response per docs

---

.github/workflows/create-buildpack-release.yaml
buildpacks/java/Makefile
buildpacks/python/Makefile

Update our buildpack build steps to include generation of the buildpack.toml file.

Add make target for generating a buildpack.toml

---

templates/java/cloudevents-gradle/src/main/java/functions/Handler.java
templates/java/cloudevents-maven/src/main/java/functions/Handler.java

Noticed this didn't match the README again somehow

Update comment to match readme

---

buildpacks/python/ytt/dependency-metadata.yaml

Adding one missing library and fixed healthz dependency

fix(python-buildpack): Fix CPE list

---

buildpacks/java/ytt/dependencies.yaml
buildpacks/java/ytt/dependency-metadata.yaml
invokers/java/pom.xml

Add explicit version for the invoker dependencies.
Additionally add the CPEs of the dependencies

chore(java-buildpack): Add pURL and CPEs for Java buildpack dependencies

---

Makefile
buildpacks/Makefile
buildpacks/java/Makefile
buildpacks/python/Makefile
invokers/Makefile
invokers/java/Makefile
invokers/python/Makefile
rules.mk

Make clean should remove the correct files.

chore: fixed `make clean`, reordered make targets

---

.gitignore
CONTRIBUTING.md
Makefile
builder/Makefile
builder/README.md
builder/ytt/builder.yaml
builder/ytt/java.yaml
builder/ytt/nodejs.yaml
builder/ytt/python.yaml
buildpacks/Makefile
buildpacks/README.md
buildpacks/java/Makefile
buildpacks/java/java/detect.go
buildpacks/python/Makefile
buildpacks/rules.mk
invokers/Makefile
invokers/java/Makefile
invokers/python/Makefile
local.example.mk
rules.mk
tests/README.md
tests/template_test.go

Added make targets that allow building the buildpacks with local invokers
Co-authored-by: Andrew Su <suan@vmware.com>

PDY-1210 Add logic to build buildpacks from invokers local path

---

templates/java/cloudevents-maven/README.md
tests/template_test.go

chore: Renaming remaining Hire -> Handler

---

buildpacks/python/python/function.go

chore: gofmt python buildpack

---

DEPLOYING.md
README.md
samples/java/cloudevents/txt-to-pdf-maven/Makefile
samples/python/cloudevents/s3-lambda/README.md
samples/python/cloudevents/sqs-lambda/README.md
samples/python/cloudevents/txt-to-pdf/Makefile
samples/python/http/adder/README.md
templates/java/manifest.yaml
templates/python/manifest.yaml

chore(docs): Update docs ref to builder 0.1.0

---

samples/python/cloudevents/s3-lambda/func.yaml
samples/python/cloudevents/s3-lambda/main.py
samples/python/cloudevents/sqs-lambda/knative-function-encrypter/func.yaml
samples/python/cloudevents/sqs-lambda/knative-function-encrypter/main.py
samples/python/cloudevents/txt-to-pdf/README.md
samples/python/cloudevents/txt-to-pdf/app/func.yaml
samples/python/cloudevents/txt-to-pdf/app/main.py
samples/python/http/adder/README.md
samples/python/http/adder/func.py
samples/python/http/adder/func.yaml

bug(samples): Update Python samples for builder 0.1.0 behavior

---

.github/workflows/test-builder.yml
.github/workflows/test-buildpacks.yml
.github/workflows/test-templates.yml
buildpacks/java/go.mod
buildpacks/java/go.sum
buildpacks/java/java/build.go
buildpacks/java/tests/build_test.go
buildpacks/java/tests/detect_test.go
buildpacks/java/tests/setup.go

Adds testing of detect and build in the java buildpack

chore(tests): add more tests for java buildpack

---

.github/workflows/integration-tests.yml
Makefile
builder/Makefile
buildpacks/README.md
buildpacks/java/Makefile
buildpacks/python/Makefile
tests/Makefile
tests/README.md
tests/integration/helper.go

Run integration tests against current code vs released buildpacks

---

templates/java/manifest.yaml
templates/python/manifest.yaml

Additionally added some buildenvs, not that it matters since the templates are using the defaults but this would provide more visibility to folks trying to modify it.

chore: update to use the latest builder 0.2.0

---

templates/java/manifest.yaml

Signed-off-by: Thomas Risberg <risbergt@vmware.com>
Fixes: #155
It adds the actuator endpoints tothe healthEndpoints section of the `manifest.yaml` for the Java templates.
```release-note
Actuator endpoints added to the healthEndpoints section of the `manifest.yaml` for the Java templates.
```

Adding healthEndpoints for Java templates

---

invokers/java/pom.xml

chore(invoker): update java invoker dependencies

chore(invoker): update java invoker dependencies

---

buildpacks/java/ytt/dependency-metadata.yaml

chore(java buildpack) Update cpes

---

DEPLOYING.md
README.md
samples/java/cloudevents/txt-to-pdf-gradle/Makefile
samples/java/cloudevents/txt-to-pdf-maven/Makefile
samples/java/http/request-response-gradle/Makefile
samples/java/http/request-response-gradle/README.md
samples/java/http/request-response-maven/Makefile
samples/java/http/request-response-maven/README.md
samples/python/cloudevents/s3-lambda/README.md
samples/python/cloudevents/sqs-lambda/README.md
samples/python/cloudevents/txt-to-pdf/Makefile
samples/python/http/adder/README.md

Update docs and makefiles with the new version of the builder

chore(docs) Update builder version in docs and makefiles

---

invokers/python/Dockerfile

fixing tox sdist command not recognized

---

.github/actions/srp-helper/install/action.yml
.github/actions/srp-helper/install/install.sh

Fixes: [Visible AWS S3 virtual-hosted-style endpoints](https://guides.spectralops.io/docs/endpoint-exposed)

move s3 url to secrets

---

.github/actions/semver-bump/action.yml

update the nodejs version to 16

update nodejs version for semver github action

---

builder/ytt/builder.yaml

Update the version of the jammy stack for the builder.

chore(builder) Bump the version of jammy stack

---

.github/actions/srp-helper/install/action.yml
.github/actions/srp-helper/install/install.sh
.github/workflows/vmware-srp-report.yaml

Fetch the srp cli from a new location

chore(srp) Fix SRP 

---

DEPLOYING.md
README.md
builder/README.md
buildpacks/README.md
invokers/README.md
samples/java/cloudevents/txt-to-pdf-gradle/Makefile
samples/java/cloudevents/txt-to-pdf-maven/Makefile
samples/java/http/request-response-gradle/Makefile
samples/java/http/request-response-gradle/README.md
samples/java/http/request-response-maven/Makefile
samples/java/http/request-response-maven/README.md
samples/python/cloudevents/s3-lambda/README.md
samples/python/cloudevents/sqs-lambda/README.md
samples/python/cloudevents/txt-to-pdf/Makefile
samples/python/http/adder/README.md

In documentation and Makefiles update references to the new builder image.  Enhance the documentation around the release process.

chore(docs) Update references to new builder image

---

invokers/java/pom.xml

Bump Spring version in pom.xml to alleviate https://spring.io/security/cve-2023-20860

Bump spring version to remove cve-2023-20860

---

tests/go.mod
tests/go.sum

update docker dependency with patch for CVE-2023-28840

---

.github/workflows/test-invokers.yml

codecov init

---

.github/workflows/code-coverage.yml
.github/workflows/test-buildpacks.yml
.github/workflows/test-invokers.yml
.gitignore
buildpacks/common/Makefile
buildpacks/java/Makefile
buildpacks/python/Makefile
codecov.yaml
invokers/java/Makefile
invokers/java/pom.xml
invokers/python/Makefile
invokers/python/tox.ini

Fixes: There is no way to know the test coverage of this project

Add Coverage to the project (Buildpacks and Invokers)
